<a href="https://colab.research.google.com/github/Ishan402/Python-Applied-AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy Tutorial**

In [ ]:
import numpy as np

a=np.array([1,5,7], dtype='int16')
b=np.array([4,10,13])
c=a*b
print(c)

[ 4 50 91]


In [ ]:
d= np.array([[1,4,6], [9,5,8], [11,10,17]])
print(d)

[[ 1  4  6]
 [ 9  5  8]
 [11 10 17]]


In [ ]:
d.ndim
#ndim also referred as Rank

3

In [ ]:
d.shape

(3, 3)

In [ ]:
print(d.dtype)
print(a.dtype)
#dtype = data type

int64
int16


In [ ]:
d[2,1]

10

In [ ]:
d[1,2]=100
print(d)

[[  1   4   6]
 [  9   5 100]
 [ 11  10  17]]


###3D Examples

In [ ]:
import numpy as np

num = np.array([[[1,3], [9,7]],[[4,6], [9,11]]])
print(num)

[[[ 1  3]
  [ 9  7]]

 [[ 4  6]
  [ 9 11]]]


In [ ]:
num[:,1,:]

array([[ 9,  7],
       [ 9, 11]])

##Initializing different types of Arrays

In [ ]:
#All Zeroes Matrix
np.zeros([5,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros([7])

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full([2,3],99.7)

array([[99.7, 99.7, 99.7],
       [99.7, 99.7, 99.7]])

In [ ]:
#Random Decimal Nunbers
np.random.rand(4,2)

array([[0.89995612, 0.10438527],
       [0.80698354, 0.28192157],
       [0.01364229, 0.34065202],
       [0.54188805, 0.57907013]])

In [ ]:
np.random.randint(-4,7, size=(3,3))

array([[ 6,  1, -4],
       [ 6, -3,  3],
       [ 3,  2,  5]])

In [ ]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Reoeat an Array
arr = np.array([[1,2,3]])
a1 = np.repeat(arr,4, axis=0)
print(a1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


##HandsOn

In [ ]:
output = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9

output[1:4, 1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Transpose of a matrix

mat = np.array([[1,5,4], [9,6,8], [6,1,8]])
print(mat)
print("-----------------------------------------------")

print(mat.transpose())

[[1 5 4]
 [9 6 8]
 [6 1 8]]
-----------------------------------------------
[[1 9 6]
 [5 6 1]
 [4 8 8]]


##Mathematics

In [ ]:
h1 = np.array([1,2,3,4])
print(h1)

[1 2 3 4]


In [ ]:
h1 +2

array([3, 4, 5, 6])

In [ ]:
h1*2

array([2, 4, 6, 8])

In [ ]:
b1=np.array([4,2,8,6])
h1+b1

array([ 5,  4, 11, 10])

In [ ]:
#a power b = a**b
h1**3

array([ 1,  8, 27, 64])

In [ ]:
vals = 30
vals = np.sin(vals * np.pi/180)
print(vals)

0.49999999999999994


In [ ]:
#Take sin, cos and tan of every value
val = np.array([0, 15, 30, 45, 60, 75,90])
val = np.sin(np.radians(val))
print(val)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]


In [ ]:
val1 = np.array([0, 15, 30, 45, 60, 75, 90])
val1 = np.cos(np.radians(val1))
print(np.around(val1,3))

[1.    0.966 0.866 0.707 0.5   0.259 0.   ]


In [ ]:
#Exception - tan(90)=infinity
val3 = np.array([0, 15, 30, 45, 60, 75])
val3 = np.tan(np.radians(val3))
print(np.around(val3,4))

[0.     0.2679 0.5774 1.     1.7321 3.7321]


##Linear Algebra

In [ ]:
#Matrix Multiplication

a = np.full([3,2], 3)
b = np.full([2,4], 2)
print(a)
print(b)
c= np.matmul(a,b)
print(c)

[[3 3]
 [3 3]
 [3 3]]
[[2 2 2 2]
 [2 2 2 2]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]


In [ ]:
#Print determinant
d = np.array([[1,5,8], [9,7,3], [5,8,2]])
np.linalg.det(d)


271.00000000000006

In [ ]:
##Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.max(stats, axis=0)

array([4, 5, 6])

In [ ]:
np.sum(stats)

21

##Reorganizing arrays

In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape([4,2])
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#Vertically stacking Vectors and matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])
#vstack = Vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
#Horizontal Stacking Vectors and Matrices
h1 = np.ones([2,4])
h2 = np.zeros([2,2])
print(h1)
print ('------------------------------------------')
print(h2)
print('------------------------------------------')
np.hstack([h1, h2, h2])
#hstack = horizontal stack

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------------------
[[0. 0.]
 [0. 0.]]
------------------------------------------


array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

##Miscellaneous

In [ ]:
'''
File data Values -  Will get error, try in Jupyter Notebook and paste the below content in Notepad
1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5
3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12
1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88
'''

#Load Data from File
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)

#Boolean values
filedata > 50

#indexing
filedata[filedata > 50]

#Another example
np.any(filedata > 50, axis=0)
#try with np.all and also try another with replacing axis =0 with 1


#not successful - Just for your reference

OSError: ignored

In [ ]:
#You can index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]

array([2, 4, 9])

##Handson
print matrix

1  2  3  4  5

6  7  8  9  10

11 12 13 14 15

16 17 18 19 20

21 22 23 24 25

26 27 28 29 30

In [ ]:
ques = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])
print(ques)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
ques[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
#Print 2, 8,14,20
ques[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
#Print 4,5,24,25,29,20
ques[[0,4,5], 3:4]

array([[ 4],
       [24],
       [29]])